#!/usr/bin/env python
import argparse
import sys
import os
import pathlib

from src import gitop;
from src.terminal import Terminal;

from src.commands.init import InitCommand;
from src.commands.feature import FeatureCommand;
from src.commands.hotfix import HotfixCommand;
from src.commands.release import ReleaseCommand;
from src.commands.commit import CommitCommand;
from src.commands.test import TestCommand;

class CheckPathAction(argparse.Action):
	def __call__(self, parser, namespace, values, option_string=None):
		# Convert the provided path to an absolute path
		path = pathlib.Path(values).resolve()

		# Check if the path exists
		if not path.exists():
			parser.error(f"The specified path '{path}' does not exist.")

		setattr(namespace, self.dest, path)

def main () :
	parser = argparse.ArgumentParser(
		prog='GitPy',
		description='GitPy: A simple Git repository manager based on GitFlow requirements.',
		epilog='See below all commands ready to be used.'
	);

	parser.add_argument('command', help='Command to be executed.', choices=['init', 'commit', 'feature', 'release', 'hotfix', 'merge', 'migrate', 'test']);
	parser.add_argument('-p', '--path', help='Working directory for git.', type=pathlib.Path, default=os.getcwd(), action=CheckPathAction);
	args = parser.parse_args();

	Terminal.warning("Working directory: " + str(args.path));
	git = gitop.GitOp(args.path);

	switcher = {
		'init': lambda : InitCommand(git).run(),
		'feature': lambda : FeatureCommand(git).run(),
		'hotfix': lambda : HotfixCommand(git).run(),
		'release': lambda : ReleaseCommand(git).run(),
		'commit': lambda : CommitCommand(git).run(),
		'test': lambda : TestCommand(git).run(),
	}

	func = switcher.get(args.command, False);

	if ( func == False ):
		Terminal.err('Unexpected command', 'The command {command} was not found.'.format(command=command));

	func();
	Terminal.success();

if __name__ == "__main__":
	main();