#!/usr/bin/env python
import sys

from src import gitop;
from src import terminal;

def main () :
	command = None;
	argv = sys.argv[1:];

	if (len(argv) == 0):
		terminal.Terminal.err('Argumento Inválido', 'Defina um comando antes de continuar...');

	git = gitop.GitOp();

	if ( git.exists() == False ):
		terminal.Terminal.printErr('Repositório não encontrado', 'O repositório ainda não foi iniciado na pasta atual...');
		_continue = terminal.Terminal.askYN('Deseja iniciar o repositório?');

		if ( _continue ):
			git.init();

		terminal.Terminal.success('Não há mais nada a ser feito, inicialize antes de continuar...');

	command = argv[0];
	switcher = {
		'commit': lambda : git.commit(),
	}

	func = switcher.get(command, False);

	if ( func == False ):
		terminal.Terminal.err('Comando Inválido', 'O comando {command} não foi encontrado.'.format(command=command));

	func();
	terminal.Terminal.success();

if __name__ == "__main__":
	main();